language: cpp

sudo: required
dist: xenial

notifications: 
  email:
    recipients:
    - rncbc@rncbc.org
    on_success: change
    on_failure: always

branches:
  only:
  - master

before_install:
- sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
- sudo add-apt-repository --yes ppa:beineri/opt-qt-5.12.3-xenial
- sudo apt-get update -qq

install:
- sudo apt-get install -qq qt512base qt512tools libgl-dev; source /opt/qt512/bin/qt512-env.sh

before_script:
- git fetch --unshallow --tags -q
- ./autogen.sh

script:
- ./configure
- make && sudo make install
